apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-service
  description: A service for demonstrating Backstage component registration
  tags:
    - demo
    - example
spec:
  type: service
  lifecycle: production
  owner: team-a
  system: example-system
  providesApis: []
  consumesApis: []
  dependsOn: []
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: another-service
  description: Another service as part of the example system
  tags:
    - sample
spec:
  type: service
  lifecycle: development
  owner: team-b
  system: example-system
  providesApis: []
  consumesApis: []
  dependsOn:
    - component: example-service

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com

---

apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: ac-chiragmalik
spec:
  memberOf: [guests]
  profile:
    email: chirag.malik@armorcode.io
    displayName: ac-chiragmalik
    name: ac-chiragmalik    
