apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com

---

apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: ac-chiragmalik
spec:
  lifecycle: production
  profile:
    email: chirag.malik@armorcode.io
    displayName: ac-chiragmalik
    name: ac-chiragmalik    
